from abc import ABC, abstractmethod

from neuravac_core.models import BatteryState, BumperState, CliffState, EncoderState


class RobotBase(ABC):
    @abstractmethod
    async def connect(self) -> None: ...
    @abstractmethod
    async def disconnect(self) -> None: ...
    @abstractmethod
    async def set_velocity(self, linear_mps: float, angular_rps: float) -> None: ...
    @abstractmethod
    async def stop(self) -> None: ...
    @abstractmethod
    async def set_vacuum(self, enabled: bool) -> None: ...
    @abstractmethod
    async def set_main_brush(self, enabled: bool) -> None: ...
    @abstractmethod
    async def set_side_brush(self, enabled: bool) -> None: ...
    @abstractmethod
    async def get_battery_state(self) -> BatteryState: ...
    @abstractmethod
    async def get_bumper_state(self) -> BumperState: ...
    @abstractmethod
    async def get_cliff_state(self) -> CliffState: ...
    @abstractmethod
    async def get_encoder_state(self) -> EncoderState: ...
    @abstractmethod
    async def emergency_stop(self) -> None: ...
